In [2]:
import numpy as np

In [3]:
sample_array = np.array([1,2,3])

sample_array

array([1, 2, 3])

In [4]:
sample_array.dtype

dtype('int64')

In [61]:
ones = np.ones((2,3))

ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
ones.dtype

dtype('float64')

In [7]:
type(ones)

numpy.ndarray

In [10]:
zeros = np.zeros([2,3])

zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)

range_array

array([0, 2, 4, 6, 8])

In [49]:
np.random.seed(seed=10)

random = np.random.randint(0, 10)

random

9

In [54]:
random_2 = np.random.randint(10, size=(5,3))

random_2

array([[8, 4, 1],
       [3, 6, 5],
       [3, 9, 6],
       [9, 1, 9],
       [4, 2, 6]])

In [55]:
random_2.shape

(5, 3)

In [56]:
random_3 = np.random.randint(10, size=(5, 3))

random_3

array([[7, 8, 8],
       [9, 2, 0],
       [6, 7, 8],
       [1, 7, 1],
       [4, 0, 8]])

In [57]:
np.unique(random_3)

array([0, 1, 2, 4, 6, 7, 8, 9])

In [64]:
random_3[:2, :2]

array([[7, 8],
       [9, 2]])

In [65]:
massive_array = np.random.random(100000)

massive_array.size

100000

In [66]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

6.29 ms ± 157 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
34.2 µs ± 222 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
